### ISSUE TITLE
OpenAPI: Some nullable types are appearing incorrectly in the open api schema

### ISSUE THREAD

**Issue by sinclairnick** [sinclairnick/webroute#8]
Example:

```
          application/json:
            schema:
              anyOf:
                - type: object
                  properties:
                    draftId:
                      type: string
                    title:
                      type:
                        - string
                        - 'null'
```

Causes error:

```
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
```
